# Generated by Django 3.1.4 on 2020-12-03 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201203_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 3, 36, 43, 952648)),
        ),
    ]
